language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: oispaolutta
  api_key:
    secure: ZYtVgPucER2pwRfcjVChoohkTlf7MYYNEnW/7gcTfPSTimItfDl8flWbig+uKBcEIa7rjJcIy9vDedXQmF5mUpAh2j5FlrnoeM24d+Z8w81m+5qUg4RI7ryswNjM93w0J8cDz69QMR3prqNCp9C8Dr8d7h2sqltS+f6rxxj9YUQMuOnH11TYiUXQTlBQALCFMIekgGU/eivWE7a8CpROg1OqICqoFOCEJ6dtwGL8sKg99FCzt2C1E526FBHWapb9Y+TzCKV1SS306HdEqdBxePeDYGYCWofRCLC4MmApjs0siQ7a2ip76xnYyNCH59Xt2s/zyjLrC78DPOLY3mV+s9OwHGT+0rpWehAnWeGeHDkQjIQViwT8Oxk9RDE1kj4C/7quI/yCZnG0lneuylzuVL+ZKG2k6TdCIADjW18KROkPNsaddk+uD3DJ9nRhw0oSEsQtpTemPZtWYH2qPaYtbkUdJC2ZC97+cRa9cbVr1Grwb1Fd1YnayjCCHi3Ox2T2ebnnNRZ86tb578eHzcoZYAOtJ22aYt1eSoJjAtvgtbcXEmBsBQkhWkfDdCLmuLvzlRFLZQJ060pSF/9dgpBYKxhmHFhslgOl1GMZyEfv79Hj2W1STsG7ohVcq2BrQU86PBNa2md86kzTn/D6b15Avjx91EKW3vNzuBsOAg41+zA=
