language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: peh/PENE59Ym4blY2O0bWO+Zm8gMgqEl/vpsVhHCffLE+bUzpG0xrQJjksQ7rikm6GGsqzUWTFm4fxvI2YTSO9BAi9mWkEcsTRvVUdom9wCvCaqM5yBWwxQjWx1O2/SfXiWOSMy2CkNK+GqXYCc4zuA1w7w8FLa6mrIEIDoc09UbCgt3gJZjqEP6YTxKeUBK9b0niJpVDJ59484ogVfYQnfBLjqTnMz07yJPV6oebO3tDbC5zVVuSPTcbvT9DkcwNxebAZDXf5vkgj8/B+QG8JvlKh03Tw1+tVdx0C3PQnfv0DW+FJ+wmVNHbSiWZeDuhYvYUdPa8c47tRKR1oZNifZuU3euOx9dutWEP97A2WFeH4yOJ1SLh0eWbUcMtEX/hwIw4GSbZK2XREeMWDPIZcovZpf//9lvr+4Fk5L2w/ePrN8fhz13EoPoXBvTyEVbpD9uNZ4fwO9n362rfHb2x+S2Vv6x9nP6TwAYB/XCAfY4ToxLH5x3YhgmyzJ4vCIXjsWoKN0wUoXxiOWQvkgH3MqHoEaNeWIHKeoEVK1xeMPUnCnV0sFjjuTfXc3go6kwSjbVUrSx4QjDt13ChWGFeWSU+WgqftynNbt4tWmghMJHQjq+K59BUjgPs/Re+bFLqDsVQLhfAmu05l5jFUO1s+FT7IGxWPCvyzFO94T3P8U=
  app: oispakaljaa
  on:
    repo: OispaKaljaa/oispakaljaa
